fn main(){
    a(42); /*doit lever erreur*/
}
